produce_day_pdt:
  cron: "30 4 * * *"
  class: "DayPdtWorker"
  queue: default
produce_sday_pdt:
  cron: "30 4 * * *"
  class: "SdayPdtWorker"
  queue: default
produce_mth_pdt_rpt:
  cron: "30 3 3 * *"
  class: "MthPdtRptWorker"
  queue: default
produce_smth_pdt_rpt:
  cron: "30 2 3 * *"
  class: "SmthPdtRptWorker"
  queue: default
